creation_rules:
  - path_regex: 'clusters/polyphony/apps/infra/ddns/secrets.yaml'
    encrypted_regex: '^(data|stringData)$'
    age: ['age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57']