apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: caddy-ingress
  namespace: flux-system
spec:
  interval: 30m
  url: https://caddyserver.github.io/ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: caddy-ingress
  namespace: caddy-system
spec:
  interval: 5m
  chart:
    spec:
      chart: caddy-ingress-controller
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: caddy-ingress
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/saavy1/caddy-cloudflare
      tag: latest
    ingressController:
      config:
        acmeCA: https://acme-v02.api.letsencrypt.org/directory
        acmeEAB: false
        onDemandTLS: true
        onDemandRateLimitInterval: 1m
        onDemandRateLimitBurst: 5
      # Cloudflare DNS challenge config
      extraEnv:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: api-token
    replicaCount: 1
