apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: caddy-ingress
  namespace: flux-system
spec:
  interval: 30m
  url: https://caddyserver.github.io/ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: caddy-ingress
  namespace: caddy-system
spec:
  interval: 5m
  chart:
    spec:
      chart: caddy-ingress-controller
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: caddy-ingress
        namespace: flux-system
  values:
    ingressController:
      config:
        # Disable ACME/auto-HTTPS - we use Cloudflare Origin CA
        onDemandTLS: false
        experimentalSmartSort: false
    replicaCount: 1
