apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: "0.9.12"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    domain: saavylab.dev
    
    pod:
      kind: Deployment
      replicas: 1
      extraVolumeMounts:
        - name: users
          mountPath: /config/users.yaml
          subPath: users.yaml
      extraVolumes:
        - name: users
          secret:
            secretName: authelia-users
    
    ingress:
      enabled: true
      className: caddy
      subdomain: auth
      tls:
        enabled: false
    
    configMap:
      authentication_backend:
        file:
          enabled: true
          path: /config/users.yaml
      
      session:
        cookies:
          - domain: saavylab.dev
            authelia_url: https://auth.saavylab.dev
        redis:
          enabled: true
          deploy: true
      
      storage:
        local:
          enabled: true
          path: /data/db.sqlite3
      
      notifier:
        filesystem:
          enabled: true
          filename: /data/notifications.txt
      
      access_control:
        default_policy: deny
        rules:
          - domain: auth.saavylab.dev
            policy: bypass
          - domain: "*.saavylab.dev"
            policy: one_factor
    
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      image:
        tag: "7.4"
      master:
        persistence:
          enabled: false

    persistence:
      enabled: true
      size: 1Gi

    secret:
      existingSecret: authelia-secrets
