apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: "0.9.12"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    domain: saavylab.dev  # TODO: Change to your domain
    
    ingress:
      enabled: true
      className: caddy
      annotations: {}
      subdomain: auth
      tls:
        enabled: true
        secret: authelia-tls
    
    pod:
      kind: Deployment
      replicas: 1
      extraVolumeMounts:
        - name: users
          mountPath: /config/users.yaml
          subPath: users.yaml
      extraVolumes:
        - name: users
          secret:
            secretName: authelia-users
    
    configMap:
      authentication_backend:
        file:
          enabled: true
          path: /config/users.yaml
      
      session:
        redis:
          enabled: true
          host: authelia-redis-master
      
      storage:
        local:
          enabled: true
          path: /data/db.sqlite3
      
      notifier:
        filesystem:
          enabled: true
          filename: /data/notifications.txt
      
      access_control:
        default_policy: deny
        rules:
          # Allow auth endpoints
          - domain: auth.saavylab.dev  # TODO: Change to your domain
            policy: bypass
          # Protect all other subdomains with single factor
          - domain: "*.saavylab.dev"  # TODO: Change to your domain
            policy: one_factor

    persistence:
      enabled: true
      size: 1Gi

    secret:
      existingSecret: authelia-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "20.6.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        size: 1Gi
