apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    #ENC[AES256_GCM,data:iOiz9LV1eCyvnzE2LSNH/+0096Vvj4FLYTxRUiIZFbbuw4wRzt6Ybora,iv:Lz7XP6lnw5WCs0tQX05KXaE4Kg4wnqY3sHDPvsaWJoc=,tag:y1JNU7zlvxjO38ZHkbPcig==,type:comment]
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:Z0veCYeaF+Pjss3EmZLzVN9t8/7Em30YEMnStPcI4fkNFcFgHqEdwcqJBXKa0tfiXqvqXpWvc0Bm+XiQY7Thdg==,iv:038DN8+uf0hVIhAcPcw/zq1uUkWugTLaz6qwbxQ8VTI=,tag:z4j+QeuBeJ2GJq1dtjfL1w==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:KMcJsxGoLAEQYARSAPZhBXqTROhvSx3Xnm4pS8RXIN10TwvcYI4tEv2RlzO571HP7qmTYV+Pt5DGdo+8TdVQ2Q==,iv:bPdF5RUkkvoIyGFiKLUrd3fFfNxh+4EeRcHZyP2IU6Y=,tag:nhEfV1QiII6ZOxNw2uDExg==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:9AF62007D3GfKh+BfPebATapR9S6tb0s1spn7eRaaufL7CEgaw+NFYWaapH2bBNKDsFQdOuoP+0CW8LBRIF29w==,iv:j6LSLYchV42bEcYMnt/EPnCCn/856aTt1YYXMhKULsg=,tag:4SlLaq578Eo6Slv5nCc1Tw==,type:str]
    session.redis.password.txt: ENC[AES256_GCM,data:No2cSfxK0WedqYLqV4shILGpPyBN7TZJO9jmxr9s8lbm6aQxqa+VP6K+fgbgML1GT7kdEQJXCwl2TzyG2ItvNA==,iv:njS+dZBl7wKM8rFrVsPwIGSiHDvpJefbvumXZgfwnzI=,tag:6at9ZKkYDU7vvlaLB6MdPQ==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMWsrV2c1eTRCa0ZzbGI0
            TFNKMmZFczJlUUJnTFdRVWhsR2N4OTlrdFJBCmd5RlJXaU5EbHlhWmM2aVIybmIr
            U1FZREdSNmNTYlBaVHdEOUVDcWlLNUUKLS0tIFRvRVo2VnQ5SXdPZTBSc0pvTzF4
            dk5yL0Q4Z25DRlRnR3BTZUtvSGFIZVUK1MaIjepBj1Qj9B1LbeMdt45I5jbrV/wP
            yq98JnJYwPjUbCHlZ22HtbPGuhRCwXD8cXORRDtIMRsm5UtQ4+9DeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T06:59:00Z"
    mac: ENC[AES256_GCM,data:VjFigCDAhPGmsfYvI3ON+v1yFBuwxpEi835xx2shXOjz5YMNiYIC6nRGeHWZ+oJ4LTCfRb3kpL7ZGG85YLFPzc1BbBSwwG1chF+jOf2koC62+SDaN9SUePzrTtfhQjOIRDRDOZuFt43Hw01tPc739CcC8UtvOPa7JWC9FLqj1es=,iv:U8fFU/cq/OotEk88hfTSJULzyfZsxLbybk7Dqm2bOYc=,tag:Gw/JOcs0g7SOVKwkNsIMHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: authelia
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fa+lhEUQy6zngIjU7TbnxSRwS7OdiFsWiV6k/7LXuTb/9A5RhBrgFUA5CpenpTk6Hcj2DCxUjrP5ylBAK4eVkFQNkT6rIn0YT4YuwYE4tghTbK87wuQpjx5Ys6lNCLMc1rG/7kLck9auxGQ=,iv:ZUakE58GmvVOUtNAjyPozq2GawUbAf2mTRfxeSELRaE=,tag:ObgUeU0KhfmfO3qq32j8yw==,type:comment]
    users.yaml: ENC[AES256_GCM,data:rDyZGwsBWzTZRVs20okm8QhxXzs5YOaZcXL1adjqajX21dHHS6QNKIVpfVzLvHpzupq6rM9OpEzWHwx56OGADR5+0dtfWuZwLNnzSuYIKF31flh3Z9H9HZ720heNin9oFudHp4v3BUZsCwcQ3kdNMlwNAbmviG+uW3fcRr2hk3WXTH26YrDrMFFBngyw6FLDFORiqbuLf8SE3TL+uJfld+ZpLYaAFSYcqcwaMOXYWyNeeIf5tbVo3mZmWG8Eg3CEXxdky80DGA5q+7YjbzB2OHq8BVEKNA==,iv:tkRvueX2FNUzMDXecnLWrdmh/QiSZqgiSr2xHYRXdHM=,tag:G0xfZaFlqMft6U59K7xHIA==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMWsrV2c1eTRCa0ZzbGI0
            TFNKMmZFczJlUUJnTFdRVWhsR2N4OTlrdFJBCmd5RlJXaU5EbHlhWmM2aVIybmIr
            U1FZREdSNmNTYlBaVHdEOUVDcWlLNUUKLS0tIFRvRVo2VnQ5SXdPZTBSc0pvTzF4
            dk5yL0Q4Z25DRlRnR3BTZUtvSGFIZVUK1MaIjepBj1Qj9B1LbeMdt45I5jbrV/wP
            yq98JnJYwPjUbCHlZ22HtbPGuhRCwXD8cXORRDtIMRsm5UtQ4+9DeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T06:59:00Z"
    mac: ENC[AES256_GCM,data:VjFigCDAhPGmsfYvI3ON+v1yFBuwxpEi835xx2shXOjz5YMNiYIC6nRGeHWZ+oJ4LTCfRb3kpL7ZGG85YLFPzc1BbBSwwG1chF+jOf2koC62+SDaN9SUePzrTtfhQjOIRDRDOZuFt43Hw01tPc739CcC8UtvOPa7JWC9FLqj1es=,iv:U8fFU/cq/OotEk88hfTSJULzyfZsxLbybk7Dqm2bOYc=,tag:Gw/JOcs0g7SOVKwkNsIMHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
