apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Aup64N55LrwpvlGk3M/EF7QUKU4fGep4gv4Oya59KJ3nbReNE7DWxneB,iv:mVijOgxe9x3san2wfGmykrqEJHa2G4ejwjfh20GaxKA=,tag:b9MyQ8IgZ3Ue6/vYQdZ4CA==,type:comment]
    JWT_TOKEN: ENC[AES256_GCM,data:Gs3DcaUGxJzPn+py4WXoO2GQDAgLK0+jUhy47jgxYT9QHu6eyY/k+GtJijXUQSKars8veX6LsBOoabuP2ATbYw==,iv:ulrJNp/k986dUYwSb5sXXqPIUqQdX1oFI7Ta8msufyw=,tag:JsnV9YJmjEqKCnMxwPuDtA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:LXmycpD6TipoSQEfptzrUtOlwmGgaG5v/Ic2G79PjLuQOwipmpWtqXXVAYIHnWAagDH1v9mMeGqkxMvj18enLQ==,iv:KEhaGvp69D0+uIpJ7PEDqs+G4sS2XMGFEvt7wdEwpyc=,tag:WM6jGVHLEPoeGZhAkbZFyQ==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:6chwYNvHKT9Hbt7jAvOZLkfVYtAv3CiybXXLeIAGj7zEho7Su7WlqpB/7cTbx7q8Fx9ulkBRTw/tTFuDcH+7Kw==,iv:Yy6scGeifMDvWrzTj1eWh7FpNFHkZJ19uWfJYUOVi4Y=,tag:peWRxoGzg2/GdeOVYEoTng==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RU95ZFlZQWVObGl2MHlO
            blMwOWIyZ1kxZ1Y0YUlBbkl6VFppazEvNUhFClpqN281ekUxNFlteldLVlFZQlNa
            eVpQK1VOOFQ4UkNnUmV6RktHdTBMMXMKLS0tIExwWlZYTHFuOVFQbWFZUzByZDlr
            MERVSFZ4eUdJdUdWVVlyc200TXdMQ1kKc8zhDMvVlMWDG64tNpRDjEWcHyPT7688
            9WxMzgmxuOvdehJrKA9ynTc31NZ4DHmNgEx/uf8vV5HJn/3SVhUEbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T03:26:48Z"
    mac: ENC[AES256_GCM,data:RbUlkWoHUAOuSM9/po+3tLKzntxaEAwZtv4u7sxirCPhE1UdbP/SZcoZzMKcGP8dnu0xJ6Nbiz1luz9lFwNaxOb+Hn5l+pAH619qvHYvTClMcV6itkbvFFHgB1Z/JZJCdNdl6WbVdVQHlGiT/H+cYo+gtq2CUifm9lH75yIMmCs=,iv:6s7cnQTz0hRfd55jCo9jMG5XXkiOPm6gmrXqFHXdThI=,tag:mKFF179AqKUrcQ8ST2yDiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: authelia
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uSb2a5I9TQJE9V/C1NtZAvxDTJubJF5FCAFK2mQ1Mp4DpOnDT0qEpXh4cKQXg+/32FuqvbdIrBvT+bJnsjupOfez87xY+5AkYvvYsbHi7fqidnp4qmRwkmqgeqBogWc9u5pqYSJEn/TS2nM=,iv:gCfthewwkTfbgXjTJyWp7qoFo1aaDFf9PbgvdojJ3HA=,tag:9a2Bo0Xx8iPZImcX+Szgkg==,type:comment]
    users.yaml: ENC[AES256_GCM,data:wXTDEaDdBuFSI9U4eJeOzP0VuDJpqMfXDH09jxkVAxqQ1NV00CZQRulbSewtfvuYOk+1zb0lApCcj1tIris+wECi0qJ7an2Xzdzp/aQf8czAsjUe1FlLAy8pahNYfQ4F0YrE7gxkxzzExflyAn5u4omvY1xGBS9ikMr64cyGKF+qRNUCrIvYC2P+SV7cjayL0WKbF078TM/wwXZtAX1kXf4y+faVdnmVCjKnc8ICg7BzicZ3Ae87qKmkvZEj8xIZ8tMtR1M81ntZcX8tCS+EtFrz,iv:kqjg13SJjIWcvpkCrytsPzix6uhE8cGxGj4Z7n9FnJM=,tag:Djao1YXGkkfxB/q5hwkCDw==,type:str]
sops:
    age:
        - recipient: age1776wth2d8psy2swdcuw5t5ptj4hdegnjzh2eppz4gahas6waks7q37cf57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RU95ZFlZQWVObGl2MHlO
            blMwOWIyZ1kxZ1Y0YUlBbkl6VFppazEvNUhFClpqN281ekUxNFlteldLVlFZQlNa
            eVpQK1VOOFQ4UkNnUmV6RktHdTBMMXMKLS0tIExwWlZYTHFuOVFQbWFZUzByZDlr
            MERVSFZ4eUdJdUdWVVlyc200TXdMQ1kKc8zhDMvVlMWDG64tNpRDjEWcHyPT7688
            9WxMzgmxuOvdehJrKA9ynTc31NZ4DHmNgEx/uf8vV5HJn/3SVhUEbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T03:26:48Z"
    mac: ENC[AES256_GCM,data:RbUlkWoHUAOuSM9/po+3tLKzntxaEAwZtv4u7sxirCPhE1UdbP/SZcoZzMKcGP8dnu0xJ6Nbiz1luz9lFwNaxOb+Hn5l+pAH619qvHYvTClMcV6itkbvFFHgB1Z/JZJCdNdl6WbVdVQHlGiT/H+cYo+gtq2CUifm9lH75yIMmCs=,iv:6s7cnQTz0hRfd55jCo9jMG5XXkiOPm6gmrXqFHXdThI=,tag:mKFF179AqKUrcQ8ST2yDiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0